[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build"
  
  # Default build command
  command = "npm run build"

# Redirects and rewrites — processed in the order they appear
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (you can also set these in Netlify UI)
[build.environment]
  REACT_APP_API_URL = "https://treasurehunt-1337.netlify.app"
  REACT_APP_WS_URL = "https://treasurehunt-1337.netlify.app"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_API_URL,REACT_APP_WS_URL"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
